s = 'CCCTGGTCAGCCCGGTGCGCCTGCCTCGAAATTCTAGAGGCTATTCTTGTGTCAACCATAGATACACTGACTGCGGAGCACGGTCATACGCCATTGCTCCTACACAGAAAGTGTTCATCTTATAGCCAGCTCTAGTCGGGGCCGGCGAGGTCACGTCCGAAGCGAGTTCTCGGAGTGGTCTTTCAGCGGCAACGAATCGAGGATGACTATCTTGCGGGCTCTTTGCAGAGCGGTCACCTGTCTATGGAAGATAAAAAGAGTAATCATCTTTTGGCGGGCCAAATCGCAATAGCATTAACGACTAACTTTATGTTAACAACCTGAGAGCTTCCCAACGTACTTCAGTGCTATCTGGTGTTATTCAATCGACGTTCGGCAGAGAAATGGGAGCGCAGAATGCGGGACCTGATCTTGTCGTGCCCTCGAGACTCTAGTCGGTGCTCTGGCATTAGACGCTTTCGTAGGTTGTCACGAGAATATTCAGTAAACATCACGAGGCAGCGACTCCCAGTCGAAGTAACAACGATTCTGCATCAGACATACCCATGCGGCTAGCCTTTGCAAGCCAAATTCCACGGTCGTCTTTCAGAATACGGCATCGCGCCTTGGTGGCGTTTGACGGACGCGTTGTCGAAAGATCAACCTCCCTTTCCCACTTAACTACACTGAGAGCGGTGGTTTTTCGCAATAATCTATTCGGGGTTTGGTTACCGCTAGAACGCGCCCGCGAGGGCAAGTCCATACGAGTGAGCGTAACTTTTTGACTATTTATCGTTAATTGGACTGAAACTTCTCGGCGTGGTGCTATCATTGACCTTCCCATGCCAGGTGTAATTCAATGGACATTGGAATCTCTAGGAGTATACTCGTCATCTTTCATATATTCCTCACGGCGGCCTAGGACACTCCGGTAATAGAAAGACTTCGAAAATTGACAAGGAATCTCATG'

sp = s[::-1]

c = ''

for x in sp:
    if x == 'A':
        c += 'T'
    elif x == 'T':
        c += 'A'
    elif x == 'G':
        c += 'C'
    elif x == 'C':
        c += 'G'

print(c)